import traceback
import sys

class CustomException(Exception):
    